name: Build
run-name: ${{ github.actor }} is Building out GitHub Actions 🚀
on: [push]
jobs:
  Build-For-Windows:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Now Making build for windows"
    - run: echo "Build done"
    - run: echo "Now Running the testing job"
  
  Testing-on-Windows:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Now testing build for windows"
      - uses: ./.github/workflows/Testing.yml
      
