name: Testing
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_call:
jobs:
  Testing-For-Windows:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Now Testing build for windows"
    - run: echo "Testing done"
    - run: echo "Now Running the deployment job"
  
  Deployment-on-Windows:
    uses: ./.github/workflows/Deployment.yml

